workflows:
  flutter-app:
    name: Flutter App

    pre_clone_scripts:
      - name: Setup SSH
        script: |
          git config --global --unset-all url."greenhouseci-team@github.com:".insteadOf || true
          git config --global url."git@github.com:".insteadOf "https://github.com/"
          touch zoolip && echo '-----BEGIN OPENSSH PRIVATE KEY-----
          b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
          QyNTUxOQAAACCu3MJvSs5KvnTCBPEeSojA3taEsmuO2lh/Sjfh0ph7OgAAAKBlU7upZVO7
          qQAAAAtzc2gtZWQyNTUxOQAAACCu3MJvSs5KvnTCBPEeSojA3taEsmuO2lh/Sjfh0ph7Og
          AAAEBvAaWBnzAuSQmtY0iHtylMOAdUmUo2D6dms3W/vNvFqa7cwm9Kzkq+dMIE8R5KiMDe
          1oSya47aWH9KN+HSmHs6AAAAGXNhbnRpYWdvYWJzYWxvbUBnbWFpbC5jb20BAgME
          -----END OPENSSH PRIVATE KEY-----' > zoolip
          sudo chmod 0600 zoolip
          eval "$(ssh-agent -s)"
          ssh-add zoolip
          sudo rm -rf /Users/builder/clone

    scripts:
        - name: Debug SSH
          script: |
            ssh -T git@github.com || true      

        - name: Build APK
          script: flutter build apk --release

    artifacts:
          - build/app/outputs/flutter-apk/*.apk